[package]
name = "zainod"
description = "Crate containing the Zaino Indexer binary."
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[[bin]]
name = "zainod"
path = "src/main.rs"

[lib]
name = "zainodlib"
path = "src/lib.rs"

[features]
# Removes network restrictions.
no_tls_use_unencrypted_traffic = []

[dependencies]
zaino-common = { workspace = true }
zaino-fetch = { workspace = true }
zaino-state = { workspace = true }
zaino-serve = { workspace = true }

# Zebra
zebra-chain = { workspace = true }
zebra-state = { workspace = true }

# Runtime
tokio = { workspace = true, features = ["full"] }

# CLI
clap = { workspace = true, features = ["derive"] }

# Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "time"] }

# Network / RPC
http = { workspace = true }
serde = { workspace = true, features = ["derive"] }

# Utility
thiserror = { workspace = true }

# Formats
toml = { workspace = true }
figment= { workspace = true, features = ["toml", "env", "test"] }
