[package]
name = "zaino-serve"
description = "Crate containing Zingo's gRPC server implementation."
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[features]
state_service = []

[dependencies]
zaino-proto = { workspace = true }
zaino-fetch = { workspace = true }
zaino-state = { workspace = true }

# Zebra
zebra-chain = { workspace = true }
zebra-rpc = { workspace = true }

# Tracing
tracing = { workspace = true }

# Miscellaneous Workspace
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true, features = ["tls"] }
thiserror = { workspace = true }
futures = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde = { workspace = true, features = ["derive"] }
tower = { workspace = true }

[build-dependencies]
whoami = { workspace = true }
