
name: CI without Docker

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt-get install -y --no-install-recommends \
            build-essential \
            pkg-config \
            libc6-dev \
            m4 \
            g++-multilib \
            autoconf \
            libtool \
            ncurses-dev \
            unzip \
            git \
            python3 \
            python3-zmq \
            zlib1g-dev \
            curl \
            bsdmainutils \
            automake \
            golang \
            ca-certificates \
            && sudo update-ca-certificates

      - name: Restore Cached Binaries
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/bin/lightwalletd
            /usr/local/bin/zcashd
            /usr/local/bin/zcash-cli
          key: binaries-${{ runner.os }}-v1
          restore-keys: |
            binaries-${{ runner.os }}-v1

      - name: Build lightwalletd
        run: |
          if [ ! -f /usr/local/bin/lightwalletd ]; then
            git clone --branch v0.4.16 https://github.com/zcash/lightwalletd
            cd lightwalletd
            make
            sudo cp lightwalletd /usr/local/bin/
          fi

      - name: Build zcashd
        run: |
          if [ ! -f /usr/local/bin/zcashd ]; then
            git clone --branch v5.6.1 https://github.com/zcash/zcash.git
            cd zcash/
            ./zcutil/fetch-params.sh
            ./zcutil/clean.sh
            ./zcutil/build.sh -j$(nproc)
            sudo cp src/zcashd /usr/local/bin/
            sudo cp src/zcash-cli /usr/local/bin/
          fi

      - name: Install Nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.78 # Specify the version you wish to install

  test:
    needs: build
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Rust Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Tests with Nextest
        run: |
          cargo build --release
          cargo nextest run --workspace --release

      - name: Run Slow Tests with Nextest
        run: |
          cargo nextest run --workspace --release -- --ignored
