name: CI - Nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  pr-checks:
    uses: ./.github/workflows/ci.yaml

  cargo-hack-build:
    uses: zingolabs/infrastructure/.github/workflows/cargo-hack.yaml@867b6501f3e6145ddce9c84b64fdda961e31e24b
    with:
      hack-subcommand: build
